apiVersion: v1
kind: Service
metadata:
  labels:
    app: greet
  name: greet
  namespace: default 
spec:
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 8080
  selector:
    app: greet
  type: NodePort
